web:
    image: seblavenant/php-apache
    ports:
        - 80
    volumes:
        - .:/var/www
        - .deploy/confs/apache/:/etc/apache2/sites-enabled/
    links:
        - database
        - mailer
        - mailcatcher
    environment:
        - SERVICE_NAME=app-assmat
database:
    image: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=passwd
        - MYSQL_DATABASE=assmat
        - MYSQL_USER=root
        - MYSQL_PASSWORD=passwd

phpmyadmin:
    image: corbinu/docker-phpmyadmin
    ports :
        - 80
    environment:
        - MYSQL_USERNAME=root
        - MYSQL_PASSWORD=passwd
        - SERVICE_NAME=app-phpmyadmin
    links:
        - database:mysql

mailcatcher:
    image: schickling/mailcatcher
    ports:
        - 1080
    environment:
        - SERVICE_NAME=serv-mail

mailer:
    image: tianon/exim4
